version: "3"

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./bot:/app

